### ISSUE TITLE
Step activator refactor: tracking issue

### ISSUE THREAD

**Issue by ofalvai** [bitrise-io/bitrise#973]
Tracking issue of refactoring and cleaning up of step activation between this codebase and the stepman codebase.

### PRs

- #954 
- #958 
- #977 
- [x] Remove [steplib independent step](https://github.com/bitrise-io/bitrise/blob/ofalvai/local-step-activator/cli/step_activator.go#L85) if it's really unused
  - #980
  - ~TODO: Stepman-side cleanup~ not needed
- #979 
- [x] Resolve TODO comments and clean up interfaces once every piece is moved over to stepman
  - https://github.com/bitrise-io/stepman/pull/332
  - https://github.com/bitrise-io/bitrise/pull/981
- [x] Clean up `steman.Activate()` and its CLI subcommand, it's no longer used as a CLI tool, just as a Go lib: https://github.com/bitrise-io/stepman/pull/333
